title: Parkjumi
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://parkjumi.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: Parkjumi
  # twitter: brianmaierjr
  facebook: brianmaierjr
  email: jm963937@gmail.com

google_analytics: "UA-138350895-1"

disqus-shortname: Parkjumi
